png_size: 1024
extension: .png
predict: true
train: true
create_test_from_train: false
createpng: false
uselock: false
debug_small_train: false
use_train_to_test: true
croptype: 0
trainpercent_totest: 0.1
