png_size: 256
extension: .png
predict: true
train: false
create_test_from_train: false
createpng: false
uselock: false
debug_small_train: false
use_train_to_test: true
use_model_to_predict: ./AutogluonModels/ag-20230411_022930
croptype: 0
trainpercent_totest: 0.1